#!/usr/bin/env bash
# scripts/devnet-mint/01-gen-keys.sh
# A.97-M.C devnet gate — Step 1: Generate 3 throwaway masternode keys.
#
# Outputs:
#   $OUT_DIR/node{1,2,3}/  — datadir skeletons with keystore/
#   $OUT_DIR/keys.env       — KEY{1,2,3}, ADDR{1,2,3}, PASSWORD vars
#
# Usage:
#   OUT_DIR=/root/devnet-a97m ./scripts/devnet-mint/01-gen-keys.sh
#
# deps: geth binary on $PATH or $GETH env var

set -euo pipefail

GETH="${GETH:-geth}"
OUT_DIR="${OUT_DIR:-/root/devnet-a97m}"
PASSWORD="${PASSWORD:-devnet-throwaway-pw}"

log() { echo "[01-gen-keys] $*" >&2; }

log "OUT_DIR=$OUT_DIR"
mkdir -p "$OUT_DIR"

# Write shared password file
echo "$PASSWORD" > "$OUT_DIR/password.txt"
chmod 600 "$OUT_DIR/password.txt"
log "Password written to $OUT_DIR/password.txt"

# Generate 3 keys, capture addresses
ADDRS=()
for i in 1 2 3; do
    DATADIR="$OUT_DIR/node$i"
    mkdir -p "$DATADIR/keystore"
    log "Generating key for node$i in $DATADIR/keystore ..."
    # geth account new outputs:  "Your new key was generated\nPublic address of the key:   0x..."
    OUTPUT=$("$GETH" account new \
        --datadir "$DATADIR" \
        --password "$OUT_DIR/password.txt" \
        2>&1)
    log "geth output: $OUTPUT"
    ADDR=$(echo "$OUTPUT" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
    if [[ -z "$ADDR" ]]; then
        log "ERROR: could not extract address from geth output"
        exit 1
    fi
    ADDRS+=("$ADDR")
    log "node$i address: $ADDR"
done

ADDR1="${ADDRS[0]}"
ADDR2="${ADDRS[1]}"
ADDR3="${ADDRS[2]}"

# Emit environment file
cat > "$OUT_DIR/keys.env" <<EOF
# Generated by 01-gen-keys.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# THROWAWAY DEVNET KEYS — DO NOT USE ON MAINNET/TESTNET
export DEVNET_DIR="$OUT_DIR"
export PASSWORD="$PASSWORD"
export ADDR1="$ADDR1"
export ADDR2="$ADDR2"
export ADDR3="$ADDR3"
EOF

log "Keys generated:"
log "  ADDR1=$ADDR1"
log "  ADDR2=$ADDR2"
log "  ADDR3=$ADDR3"
log "Env written to $OUT_DIR/keys.env"
log "Done."
