#!/bin/bash
# fresh-start-a97m-v9.sh
# Generates new keys + genesis + starts all 3 nodes fresh.
# VotePacket wire fix: handler_xdc.go now sends types.Vote directly.
set -euo pipefail

BIN=/root/workspace/go-ethereum-a97m/build/bin/geth
XDC3=/root/workspace/XDPoSChain/build/bin/XDC
DATADIR=/root/devnet-a97m
PASS=$DATADIR/password.txt
LOG_LEVEL=5

echo "[0] Killing all devnet processes..."
pkill -9 -f "go-ethereum-a97m.*9551\|go-ethereum-a97m.*9552\|XDPoSChain.*9553\|XDPoSChain.*31303" 2>/dev/null || true
pkill -9 -f "devnet-a97m.*31301\|devnet-a97m.*31302\|devnet-a97m.*31303" 2>/dev/null || true
sleep 1

echo "[1] Generating new keys..."
# Wipe + recreate keystores only (not XDCx etc.)
for i in 1 2 3; do
    rm -rf $DATADIR/node$i/keystore $DATADIR/node$i/XDC $DATADIR/node$i/geth $DATADIR/node$i/XDC.ipc $DATADIR/node$i/geth.ipc
    mkdir -p $DATADIR/node$i/keystore $DATADIR/node$i/logs
done

# Generate key for node1 (our geth)
OUTPUT1=$($BIN account new --datadir $DATADIR/node1 --password $PASS 2>&1)
ADDR1=$(echo "$OUTPUT1" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
echo "ADDR1=$ADDR1"

# Generate key for node2 (our geth)
OUTPUT2=$($BIN account new --datadir $DATADIR/node2 --password $PASS 2>&1)
ADDR2=$(echo "$OUTPUT2" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
echo "ADDR2=$ADDR2"

# Generate key for node3 (XDPoSChain — outputs "xdc" prefix, not "0x")
OUTPUT3=$($XDC3 account new --datadir $DATADIR/node3 --password $PASS 2>&1)
# XDPoSChain uses "xdc" prefix — convert to 0x
ADDR3_RAW=$(echo "$OUTPUT3" | grep -oE 'xdc[0-9a-fA-F]{40}' | head -1)
if [[ -z "$ADDR3_RAW" ]]; then
    # Fallback: try 0x format
    ADDR3=$(echo "$OUTPUT3" | grep -oE '0x[0-9a-fA-F]{40}' | head -1)
else
    ADDR3="0x${ADDR3_RAW#xdc}"
fi
echo "ADDR3=$ADDR3"

if [[ -z "$ADDR1" || -z "$ADDR2" || -z "$ADDR3" ]]; then
    echo "ERROR: failed to generate one or more addresses"
    echo "OUTPUT1=$OUTPUT1"
    echo "OUTPUT2=$OUTPUT2"
    echo "OUTPUT3=$OUTPUT3"
    exit 1
fi

# Write keys.env
cat > $DATADIR/keys.env <<ENV_EOF
# Generated by fresh-start-a97m-v9.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# THROWAWAY DEVNET KEYS — DO NOT USE ON MAINNET/TESTNET
export DEVNET_DIR="$DATADIR"
export PASSWORD="devnet-throwaway-pw"
export ADDR1="$ADDR1"
export ADDR2="$ADDR2"
export ADDR3="$ADDR3"
ENV_EOF
echo "keys.env written."

echo "[2] Generating genesis with MasternodeVotingSMC..."
python3 /tmp/gen-genesis-a97m.py "$ADDR1" "$ADDR2" "$ADDR3" "$DATADIR/genesis.json"

echo "[3] Init chaindata..."
$BIN init --datadir $DATADIR/node1 --state.scheme path $DATADIR/genesis.json 2>&1 | grep -E "wrote|hash=" | tail -2
$BIN init --datadir $DATADIR/node2 --state.scheme path $DATADIR/genesis.json 2>&1 | grep -E "wrote|hash=" | tail -2
$XDC3 init --datadir $DATADIR/node3 $DATADIR/genesis.json 2>&1 | grep -E "wrote|hash=" | tail -2

echo "[4] Starting node1 (our geth, ADDR1=$ADDR1)..."
nohup $BIN \
    --datadir $DATADIR/node1 --networkid 551 --port 31301 \
    --mine --miner.etherbase $ADDR1 --unlock $ADDR1 --password $PASS \
    --http --http.addr 127.0.0.1 --http.port 9551 \
    --http.api eth,net,web3,admin,XDPoS,xdc,miner,debug \
    --authrpc.port 9651 --authrpc.addr 127.0.0.1 \
    --gcmode full --snapshot=false --nodiscover --maxpeers 10 \
    --syncmode full \
    --ethstats "xdc03-devnet-mint-node1:xdc_openscan_stats_2026@stats.xdcindia.com:443" \
    --verbosity $LOG_LEVEL \
    >> $DATADIR/node1/logs/geth.log 2>&1 &
echo "node1 PID=$!" && echo $! > $DATADIR/node1.pid

echo "[5] Starting node2 (our geth, ADDR2=$ADDR2)..."
nohup $BIN \
    --datadir $DATADIR/node2 --networkid 551 --port 31302 \
    --mine --miner.etherbase $ADDR2 --unlock $ADDR2 --password $PASS \
    --http --http.addr 127.0.0.1 --http.port 9552 \
    --http.api eth,net,web3,admin,XDPoS,xdc,miner,debug \
    --authrpc.port 9652 --authrpc.addr 127.0.0.1 \
    --gcmode full --snapshot=false --nodiscover --maxpeers 10 \
    --syncmode full \
    --ethstats "xdc03-devnet-mint-node2:xdc_openscan_stats_2026@stats.xdcindia.com:443" \
    --verbosity $LOG_LEVEL \
    >> $DATADIR/node2/logs/geth.log 2>&1 &
echo "node2 PID=$!" && echo $! > $DATADIR/node2.pid

echo "[6] Starting node3 (XDPoSChain, ADDR3=$ADDR3)..."
nohup $XDC3 \
    --datadir $DATADIR/node3 --networkid 551 --port 31303 \
    --mine --miner-etherbase $ADDR3 --unlock $ADDR3 --password $PASS \
    --http --http-addr 127.0.0.1 --http-port 9553 \
    --http-api eth,net,web3,admin,XDPoS,miner,debug \
    --gcmode full --nodiscover --maxpeers 10 \
    --ethstats "xdc03-devnet-xdposchain-node3:xdc_openscan_stats_2026@stats.xdcindia.com:443" \
    --verbosity $LOG_LEVEL \
    >> $DATADIR/node3/logs/geth.log 2>&1 &
echo "node3 PID=$!" && echo $! > $DATADIR/node3.pid

echo "[7] Waiting 15s for IPC sockets..."
sleep 15

echo "[8] Checking IPC sockets..."
for i in 1 2 3; do
    if [[ -S $DATADIR/node$i/XDC.ipc ]]; then
        echo "node$i IPC: OK"
    else
        echo "WARNING: node$i IPC missing"
    fi
done

echo "[9] Wiring peers..."
E1=$($BIN  attach --exec 'admin.nodeInfo.enode' $DATADIR/node1/XDC.ipc 2>/dev/null | tr -d '"')
E2=$($BIN  attach --exec 'admin.nodeInfo.enode' $DATADIR/node2/XDC.ipc 2>/dev/null | tr -d '"')
E3_RAW=$($XDC3 attach --exec 'admin.nodeInfo.enode' $DATADIR/node3/XDC.ipc 2>/dev/null | tr -d '"')
E3="${E3_RAW/@\[\:\:\]:/\@127.0.0.1:}"
echo "E1=$E1"
echo "E2=$E2"
echo "E3=$E3"

$BIN  attach --exec "admin.addPeer('${E2}'); admin.addPeer('${E3}')" $DATADIR/node1/XDC.ipc 2>&1
$BIN  attach --exec "admin.addPeer('${E1}'); admin.addPeer('${E3}')" $DATADIR/node2/XDC.ipc 2>&1
$XDC3 attach --exec "admin.addPeer('${E1}'); admin.addPeer('${E2}')" $DATADIR/node3/XDC.ipc 2>&1

sleep 3
echo ""
echo "[10] Status:"
echo -n "node1 peers: "; $BIN  attach --exec 'net.peerCount' $DATADIR/node1/XDC.ipc 2>/dev/null
echo -n "node2 peers: "; $BIN  attach --exec 'net.peerCount' $DATADIR/node2/XDC.ipc 2>/dev/null
echo -n "node3 peers: "; $XDC3 attach --exec 'net.peerCount' $DATADIR/node3/XDC.ipc 2>/dev/null
echo -n "node1 head: ";  $BIN  attach --exec 'eth.blockNumber' $DATADIR/node1/XDC.ipc 2>/dev/null
echo -n "node2 head: ";  $BIN  attach --exec 'eth.blockNumber' $DATADIR/node2/XDC.ipc 2>/dev/null
echo -n "node3 head: ";  $XDC3 attach --exec 'eth.blockNumber' $DATADIR/node3/XDC.ipc 2>/dev/null
echo ""
echo "=== devnet-a97m v9 RUNNING ==="
echo "Monitor: tail -f $DATADIR/node{1,2,3}/logs/geth.log"
